from enum import Enum


class ActivityStatus(Enum):
    PIPELINE = 1
    IMPLEMENTATION = 2
    COMPLETION = 3
    POST_COMPLETION = 4
    CANCELLED = 5
    SUSPENDED = 6


class DocumentCategory(Enum):
    PRE_AND_POST_PROJECT = "A01"
    OBJECTIVES = "A02"
    INTENDED_ULTIMATE_BENEFICIARIES = "A03"
    CONDITIONS = "A04"
    BUDGET = "A05"
    SUMMARY_INFORMATION = "A06"
    REVIEW_AND_EVALUATION = "A07"
    RESULTS = "A08"
    MEMORANDUM_OF_UNDERSTANDING = "A09"
    PROCUREMENT = "A10"
    CONTRACT = "A11"
    PROJECT_PAGE = "A12"


class TransactionType(Enum):
    INCOMING_FUNDS = 1
    COMMITMENT = 2
    DISBURSEMENT = 3
    EXPENDITURE = 4
    INTEREST_PAYMENT = 5
    LOAN_REPAYMENT = 6
    REIMBURSEMENT = 7
    PURCHASE_OF_EQUITY = 8
    SALE_OF_EQUITY = 9
    CREDIT_GUARANTEE = 10
    INCOMING_COMMITMENT = 11
    OUTGOING_PLEDGE = 12
    OUTGOING_COMMITMENT = 13